main: ${project.package}.Main
name: ${project.name}
version: ${project.version}
authors:
  - Carm
  - ${project.organization.name}
  - SakuraGame
website: ${project.url}
description: ${project.description}
api-version: 1.13
folia-supported: true

depend:
  - LuckPerms
softdepend:
  - PlaceholderAPI

permissions:
  "UserPrefix.admin":
    description: "用户前缀系统的管理命令权限。"
    default: op

commands:
  UserPrefix:
    aliases:
      - prefix
    description: "用户前缀系统玩家指令，用于打开前缀GUI。"
  UserPrefixAdmin:
    aliases:
      - upa
    permission: "UserPrefix.admin"
    description: "用户前缀系统管理指令，可以查看前缀列表与重载配置文件。"
